### ISSUE TITLE
add an example Notebook.

### ISSUE THREAD

**Issue by mohitsawwalakhe** [lpphd/lightwaves#1]
Can you please add an example notebook demonstrating the use of the library on UCR data and on a CUSTOM dataset?.

**Comment by lpphd** [comment]
Hey, thank you for the comment! I added an additional code file that uses the "Worms" dataset from UCR, found here https://www.timeseriesclassification.com/description.php?Dataset=Worms. 
The only change required for univariate datasets is to transform them from the 2-D format (samples, timesteps) to the 3-D format (samples,1,timesteps). Moreover, since there is only one channel, LightWaveS will be executed only on 1 MPI node. Other than that, the process is similar.
Can you elaborate on the custom dataset part? As long as the dataset is in 3-D numpy format (samples,channels,timesteps) the algorithm should work normally.

I hope this helps!

**Comment by qaz3251162** [comment]
Can you please add an example notebook demonstrating the use of  MAFAULDA dataset.I'm a beginner.So I'm not sure I can replicate your program
