### ISSUE TITLE
Add a new example

### ISSUE THREAD

**Issue by lys15163238308** [lpphd/lightwaves#2]
Can you please add an example notebook demonstrating the use of MAFAULDA dataset.I'm a beginner.So I'm not sure I can replicate your program

**Comment by lpphd** [comment]
Hey, thank you for the comment! Can you elaborate on your question? If you download the MAFAULDA dataset from its original location, you can follow the function in PrepareDatasets.py and make the .npz file. Afterwards, it is just a matter of replacing the dataset in the lightwaves_l1l2.py file and removing the external loop over datasets. I uploaded an example, let me know if this helps.

**Comment by qaz3251162** [comment]
Thank you very much for your help ！The program has run successfully.Can you explain what the mafaulda_orig.npz file is used for?I would appreciate it very much.

**Comment by lys15163238308** [comment]
I really appreciate your help ! The program has run successfully.Can you help me figure out what the mafaulda_orig.npz file is for ?
I would appreciate it.

**Comment by lpphd** [comment]
Hey, I'm glad to hear that! The mafaulda_orig.npz contains the data and labels (x and y) before the train-test split with the specific random seed (42) and specific percentage (85%-15%) of the final file. I implemented the saving in case someone wanted to try a different train-test split, or multiple ones, so it would be easier to load this file instead. Let me know if this is clear!

**Comment by lys15163238308** [comment]
Hi，thank you very much for your answer ! Your answer is very clear.And i have two more questions to ask. 
         df=pd.read_csv(filename,header=None).values[::250, :].reshape((1, 8, -1)) this code in PrepareDatasets.
         df=pd.read_csv(filename,header=None).values[::250, :] Whether to truncate 50 seconds of data every 0.1 second?
         df=pd.read_csv(filename,header=None).values[::250, :].reshape((1, 8, -1))If my data has 20 channels, should I change the number 8 to the number 20?
Looking forward to your reply!

**Comment by lpphd** [comment]
Hey, you are welcome! For the first question, if I understand correctly, I chose to subsample the dataset since it has a 50 kHz frequency, which makes the sequences very long for practical purposes. However, this can be considered a hyperparameter, so you can change that to any subsampling scheme or frequency that best works for you. 
Regarding the reshaping, is is true that in theory you only need to replace 8 with 20, but keep in mind that it depends on the original format of the data. In addition, motivated by your question, I went over the code and I think that this line should be fixed, so I updated the file. Let me know if that answers your questions!

**Comment by lys15163238308** [comment]
Hi ! Thank you very much for your answer, which was very clear.I found that the sorting task for the MAFAULDA database was not differentiated by channel.Does that mean I can reshape the data into (1,x,-1)?The value of X has no effect on the final classification result?I went over the changes you made.I want to know why I transpose the data?I found it was less accurate after the change than before.If the question I ask is clear,Please let me know.Thanks again for your answer.Looking forward to your reply.

**Comment by lpphd** [comment]
Hey! After reading the .csv and after the subsampling of the timesteps, the data is in format (Timesteps, Channels), which in the case of MAFAULDA is (1000,8). I wanted to bring the dataset to the format (Samples,Channels,Timesteps) which is the format I wanted to work with. Thus, the transposition first changes the format to (Channels, Timesteps), and the reshaping just adds the Sample dimension to the front, in order to make it easy to concatenate all the samples later. So, there is not really a choice for X, since it is the number of sensors in MAFAULDA (8), unless you are going for some custom data preprocessing. Let me know if this makes sense!

**Comment by lys15163238308** [comment]
Thank you for clearing my mind.I want to ask if images can be used as input?

**Comment by lpphd** [comment]
Hey, I'm glad to hear that it is clear. If you can bring the image dataset to a 3-D format, they can definitely be used. For instance, if your dataset has 3 color channels, the format could be (Samples,3,Height*Width). Depending on the dataset, this could lead to a large number of 'timesteps', so I don't know what the accuracy would be, or if LightWaveS would do better against computer vision models, but it would execute normally.

**Comment by lys15163238308** [comment]
Hey~Long time no see.I ran into a new problem, I used lightwave on my own database, but the classification results were not very good(Maybe I didn't preprocess the data properly). would like to know which hyperparameters I can adjust to improve the performance. Do you have any suggestions?Thanks for your time.

**Comment by lpphd** [comment]
Hey! As you correctly observed, maybe a different preprocessing could give better results. Other than that, some quick hyperparameters that you can experiment with are the MAX_DILATION, PRE_FINAL_FEAT_NUM and FINAL_FEAT_NUM. You could also experiment with the parameters of the final RidgeClassifierCV. Finally, if you want to go more in depth, you can modify the get_fixed_candidate_kernels and _generate_first_phase_kernels functions to your liking, to change the weights or other kernel parameters. I hope some of these will help with your use case!
