### ISSUE TITLE
Questions about algorithmic theory

### ISSUE THREAD

**Issue by lys15163238308** [lpphd/lightwaves#4]
Hey,The lightwave algorithm is to replace the wavelet in the wavelet scattering network with the convolutional kernel generated by 84 nuclei in the minirocket,I don't know if I understand this correctly?Or is it generating arbitrary subwavelets?

**Comment by lpphd** [comment]
Hey, your understanding is correct. In general, the framework applies wavelet scattering for each kernel in given a set of kernels (also applying various dilations). In this case, for our experimentation and comparison purposes, this set is the same as the one utilized in MINIROCKET.

**Comment by lys15163238308** [comment]
Thank you very much for your reply. Your answer is very helpful to me ！Another problem is that U{λ} is the absolute value of the convolution between the input and the convolution kernel.How to calculate PPV? Doesn't PPV become 1? Or the absolute value of the convolution between the input and the convolution kernel only applies to the input at the next level？The feature is extracted from the convolution result rather than the absolute value of the convolution result ？I don't know if I understand this correctly？

**Comment by lpphd** [comment]
Hey, this is also a very good observation. The percentage of positive values (ppv) and normalized longer
sequence of positive values are indeed extracted from the convolution result, before the application of the modulus operator, exactly because they are sensitive to the sign of values. On the other hand, the max and min features directly replace the averaging kernel φ as pooling features (referring to equation 4 in the ArXiV paper). Let me know if this is clear!

**Comment by lys15163238308** [comment]
Thank you very much for your reply.Your answer was clear.Your answer is very helpful to me.
