### ISSUE TITLE
feature selection

### ISSUE THREAD

**Issue by lys15163238308** [lpphd/lightwaves#5]
Hi~  Is there any specific reason for choosing the specific order of feature selection? The first time, we ANOVA and then MRMR?

**Comment by lpphd** [comment]
Hi! The reasoning is that since the first phase of the feature extraction and selection can be performed in a distributed manner on different nodes, we need a selection method that ranks the utility of each feature "independently",  so that we get an initial collection of the most useful features globally (across nodes). Afterwards, when this first set of features is gathered to the main node, we use MRMR to reduce redundancy, since it can compare the utility and correlation of the features. That being said, you could experiment with different feature ranking methods and potentially get some interesting results!

**Comment by lys15163238308** [comment]
Thanks for your repley. If you only use one CPU to run your code (that is, only a single node), does that mean that ANOVA has no particular advantage over other feature selection method. If I understand you correctly, nodes are not channels but computing devices.

**Comment by lpphd** [comment]
Hi,
That's correct, if you have all the generated features of the first phase on a single node, you could modify the code appropriately to use other selection methods (that even take into account the other features, such as MRMR). Yes, with nodes I am referring to computational devices, such as computers on a local network. Let me know if this is clear!

**Comment by lys15163238308** [comment]
Your answer is very clear, thank you very much for your patience.
